version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: eshaafi_db
    restart: always
    environment:
      POSTGRES_USER: eshaafi_user
      POSTGRES_PASSWORD: eshaafi_pass123
      POSTGRES_DB: eshaafi_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    image: bacillus/eshaafi-backend:stage-v1
    container_name: eshaafi_backend
    restart: always
    depends_on:
      - postgres
    environment:
      DATABASE_URL: "postgres://eshaafi_user:eshaafi_pass123@eshaafi_db:5432/eshaafi_db"
      baseUrl: "http://139.59.3.40:5000"
      JWT_SECRET: "6fa068c4edd0fba6c0968a4b40f9df25"
      JWT_EXPIRES_IN: "1h"
      HMS_ACCESS_KEY: "68a0acca145cb4e8449b0a5e"
      HMS_SECRET: "QS6CxNSK1uBRvMqGXnTUFEhww0ZeQkbDZcnAHVIRCe3WXjpzq5QzJDG2xEHOzkRYfqaUdRRZixJd8o4HYy1MsaEk5p4xsm_JqJZyGn1dEOUFE3bsi3_-E-mjLpi-LQ4klQ1HbOBNb9XzvJQUhqH-6x-LuSsEDEAxvi7aDnTPulI="
      HMS_MANAGEMENT_TOKEN: "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE3NTY0NzQ3MDMsImV4cCI6MTc1NzA3OTUwMywianRpIjoiYWVlNzQ0NDAtYzhjYS00ZWM0LThkNmQtYmQwNjMzMjgyOTczIiwidHlwZSI6Im1hbmFnZW1lbnQiLCJ2ZXJzaW9uIjoyLCJuYmYiOjE3NTY0NzQ3MDMsImFjY2Vzc19rZXkiOiI2OGEwYWNjYTE0NWNiNGU4NDQ5YjBhNWUifQ.dRtyKpMOtjtCgQEFrnbudLt5zfwHluv709JiQorXUok"
      HMS_TEMPLATE_ID: "68a0af0874147bd574bacf53"
      ADMIN_EMAIL: "admin@123.com"
      ADMIN_PASSWORD: "Admin123"
    ports:
      - "5000:5000"

  frontend:
    image: bacillus/eshaafi-frontend:stage-v1
    container_name: eshaafi_frontend
    restart: always
    depends_on:
      - backend
    environment:
      NEXT_PUBLIC_HMS_SUBDOMAIN: "muhammad-videoconf-2107"
    ports:
      - "3000:3000"

volumes:
  postgres_data:
