version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: eshaafi_db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    image: bacillus/eshaafi-backend:stage-3f05b86
    container_name: eshaafi_backend
    restart: always
    depends_on:
      - postgres
    environment:
      DATABASE_URL: ${DATABASE_URL}
      BASE_URL: ${BASE_URL}
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRES_IN: ${JWT_EXPIRES_IN}
      HMS_ACCESS_KEY: ${HMS_ACCESS_KEY}
      HMS_SECRET: ${HMS_SECRET}
      HMS_MANAGEMENT_TOKEN: ${HMS_MANAGEMENT_TOKEN}
      HMS_TEMPLATE_ID: ${HMS_TEMPLATE_ID}
      ADMIN_EMAIL: ${ADMIN_EMAIL}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
      SUPER_ADMIN_EMAIL: ${SUPER_ADMIN_EMAIL}
      SUPER_ADMIN_PASSWORD: ${SUPER_ADMIN_PASSWORD}
    ports:
      - "5000:5000"

  frontend:
    image: bacillus/eshaafi-frontend:stage-3f05b86
    container_name: eshaafi_frontend
    restart: always
    depends_on:
      - backend
    environment:
      NEXT_PUBLIC_HMS_SUBDOMAIN: ${NEXT_PUBLIC_HMS_SUBDOMAIN}
      NEXT_PUBLIC_BACKEND_URI: ${NEXT_PUBLIC_BACKEND_URI}
    ports:
      - "3000:3000"

volumes:
  postgres_data:
