version: '3.8'
services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: eshaafi_user
      POSTGRES_PASSWORD: eshaafi_pass123
      POSTGRES_DB: eshaafi_db
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  backend:
    build: ./backend
    command: npm run dev
    restart: always
    environment:
      DATABASE_URL: postgres://eshaafi_user:eshaafi_pass123@db:5432/eshaafi_db
      PORT: 5000
    volumes:
      - ./backend:/app
    working_dir: /app
    depends_on:
      - db
    ports:
      - '5000:5000'

volumes:
  db_data:
