name: CI - Build & Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get commit SHA
        id: vars
        run: echo "COMMIT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Show Docker version
        run: docker --version

      - name: Build Docker image
        run: |
          cd frontend
          docker build -t ${{ secrets.IMAGE_NAME }}-frontend:$COMMIT_SHA .
          echo "Image build complete ✅"

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Tag & Push Docker image
        run: |
          docker tag ${{ secrets.IMAGE_NAME }}-frontend:$COMMIT_SHA ${{ secrets.DOCKER_USERNAME }}/ ${{ secrets.IMAGE_NAME }}-frontend:$COMMIT_SHA
          docker push ${{ secrets.DOCKER_USERNAME }}/ ${{ secrets.IMAGE_NAME }}-frontend:$COMMIT_SHA

      - name: List Docker images
        run: docker images
